; Change Capslock to esc
CapsLock::{
    SetCapsLockState("Off")
    Send("{Esc}")  
}
^CapsLock::CapsLock

#HotIf !WinActive("Visual Studio Code")
;Math Operators 
:*?C:\questeq::≟
:*?C:\eqdef::≝
:*?C:\subsetneq::⊈
:*?C:\supsetneq::⊉
:*?C:\not\exists::∄
:*?C:\notin::∉
:*?C:\not\in :: ∉
:*?C:\cdot::·
:*?C:\circ::∘
:*?C:\times::×
:*?C:\div ::÷
:*?C:\cuberoot::∛
:*?C:\fourthroot::∜
:*?C:\sqrt::√
:*?C:\cap::∩
:*?C:\cup::∪
:*?C:\bigcap::⋂
:*?C:\bigcup::⋃
:*?C:\infty::∞
:*?C:\partial::∂
:*?C:\approx::≈
:*?C:\leq::≤
:*?C:\geq::≥
:*?C:\neq::≠
:*?C:\equiv::≡
:*?C:\cong::≅
:*?C:\pm::±
:*?C:\mp::∓
:*?C:^\circ::°
:*?C:\varnothing::∅
:*?C:\forall::∀
:*?C:\exists::∃
:*?C:\in ::∈
:*?C:\to::→
:*?C:\qint::⨌
:*?C:\oiint::∯
:*?C:\oiiint::∰
:*?C:\iiint::∭
:*?C:\iint::∬
:*?C:\int::∫
:*?C:\oint::∮
:*?C:\checkmark::✓
:*?C:\square::□
:*?C:\triangle::△
:*?C:\blacksquare::∎
:*?C:\sum::∑
:*?C:\prod::∏
:*?C:\angle::∠
:*?C:\measuredangle::∡
:*?C:\implies::⟹
:*?C:\iff::⟺
:*?C:\therefore::∴
:*?C:\subseteq::⊆
:*?C:\supseteq::⊇
:*?C:\subset ::⊂
:*?C:\supset ::⊃
:*?C:\varnothing::∅
:*?C:\wedge::⋀
:*?C:\vee::∧
:*?C:\cdots::⋯
:*?C:\dots::…
:*?C:\vdots::⋮
:*?C:\ddots::⋱
:*?C:\langle::〈
:*?C:\rangle::〉
:*?C:\mapsto::↦
:*?C:\bar::̄
:*?C:\hat::̂
:*?C:\dot ::̇
:*?C:\ddot::̈
:*?C:\tilde::̃
:*?C:\prime::′
:*?C:\dprime::″
:*?C:\tprime::‴
:*?C:\qprime::⁗
:*?C:\vec::⃗
:*?C:\mathbb{C}::ℂ
:*?C:\mathbb{R}::ℝ
:*?C:\mathbb{N}::ℕ
:*?C:\mathbb{Q}::ℚ
:*?C:\mathbb{Z}::ℤ
:*?C:\lceil::⌈
:*?C:\rceil::⌉
:*?C:\lfloor::⌊
:*?C:\rfloor::⌋
:*?C:\ast::∗
:*?C:\dag::†
:*?C:\ddag::‡
:*?C:\sqcup::⊔
:*?C:\sqcap::⊓
:*?C:\triangleright::▹
:*?C:\coprod::⨿
:*?C:\sim::∼
:*?C:\simeq::≃
:*?C:\oplus::⊕
:*?C:\otimes::⊗
:*?C:\odot::⊙
:*?C:\not ::¬
:*?C:\parallel::∥
:*?C:\perp::⟂
:*?C:\Aleph::ℵ
:*?C:\not\divides::∤
:*?C:\divides::∣
:*?C:\ell::ℓ
:*?C:\leftarrow::←
:*?C:\rightarrow::→
:*?C:\leftrightarrow::↔
:*?C:\uparrow::↑
:*?C:\downarrow::↓
:*?C:\updownarrow::↕
:*?C:\nabla::∇
:*?C:\bullet::•
:*?C:\setminus::\

;Greek Alphabet
:*?C:\alpha::α
:*?C:\beta::β
:*?C:\Gamma::Γ
:*?C:\gamma::γ
:*?C:\Delta::Δ
:*?C:\delta::δ
:*?C:\epsilon::ϵ
:*?C:\varepsilon::ε
:*?C:\zeta::ζ
:*?C:\eta::η
:*?C:\Theta::Θ
:*?C:\theta::θ
:*?C:\vartheta::ϑ
:*?C:\iota::ι
:*?C:\kappa::κ
:*?C:\varkappa::ϰ
:*?C:\Lambda::Λ
:*?C:\lambda::λ
:*?C:\mu::μ
:*?C:\nu::ν
:*?C:\Xi::Ξ
:*?C:\xi::ξ
:*?C:\Pi::Π
:*?C:\pi::π
:*?C:\varpi::ϖ
:*?C:\rho::ρ
:*?C:\varrho::ϱ
:*?C:\Sigma::Σ
:*?C:\sigma::σ
:*?C:\varsigma::ς
:*?C:\tau::τ
:*?C:\upsilon::υ
:*?C:\Phi::Φ
:*?C:\phi::φ
:*?C:\varphi::ϕ
:*?C:\chi::χ
:*?C:\Psi::Ψ
:*?C:\psi::ψ
:*?C:\Omega::Ω
:*?C:\omega::ω
#HotIf